#!/usr/bin/env python
# encoding: utf-8

def configure(cfg):
    # No necesitamos configuración específica por ahora
    pass

def build(bld):
    bld.ap_library(
        name='AP_PowerMonitor',
        vehicle=['sub'],  # solo para ArduSub
        srcs=[
            'AP_PowerMonitor.cpp',
        ],
        includes=[
            '.',
        ],
        dependencies=[
            'AP_HAL',
            'AP_Math',
            'GCS_MAVLink',
        ]
    )
